export const FETCH_RATES = "FETCH_RATES";
export const FETCH_RATES_SUCCESS = "FETCH_RATES_SUCCESS";
export const FETCH_RATES_ERROR = "FETCH_RATES_ERROR";

export const ADD_RATE = "ADD_RATE";
export const DELETE_RATE = "DELETE_RATE";

export const SELECT_CURRENCY = "SELECT_CURRENCY";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const FETCH_CURRENCIES_ERROR = "FETCH_CURRENCIES_ERROR";
